### ISSUE TITLE
Offline -- what should be locked? 

### ISSUE THREAD

**Issue by Mara2020** [CMPUT301F17T02/BAARD#111]
Currently as an issue on eclass. Awaiting for confirmation.

**Comment by anarten** [comment]
Lock out maps and friends once implemented
All other functionality should be fine
(maybe not settings?)

**Comment by Mara2020** [comment]
completed in pull request by @anarten . 

As discussed in class:
- can login OFFLINE so long as user was previously logged in on phone before (cannot log in new users)
- can do all functionality offline (no restrictions)
