### ISSUE TITLE
All Habits List -- particular note

### ISSUE THREAD

**Issue by Mara2020** [CMPUT301F17T02/BAARD#25]
As a participant, I want to view as a list my habit history, sorted in reverse chronological order (most recent coming first).

**Comment by Mara2020** [comment]
Can we clarify "most recent" aspect?

**Comment by AndrewMcKernan** [comment]
It would be by the last habit event. It's ambiguously named but the habit history is referring to habit events since one of the requirements for habit events is "As a participant, I want to add a habit event to my habit history when I have done a habit as planned." (US 02.01.01)
