### ISSUE TITLE
Test Cases for Habit Event

### ISSUE THREAD

**Issue by Mara2020** [CMPUT301F17T02/BAARD#28]

**Comment by AndrewMcKernan** [comment]
Now that the use cases are completed barring any bugs we may find, I have started unit testing more intently.

**Comment by AndrewMcKernan** [comment]
Test cases for creating habit events, deleting them, and testing the classes themselves are complete. Still need EditHabitEvent unit tests

**Comment by Mara2020** [comment]
Habit event tests added by @AndrewMcKernan !
