### ISSUE TITLE
UML Part 5

### ISSUE THREAD

**Issue by Mara2020** [CMPUT301F17T02/BAARD#37]
Complete the UML with changes from part 5 code

**Comment by AndrewMcKernan** [comment]
UML should account for the new Friends classes, including:

ViewFriendActivity
ViewFriendHabitActivity
ExploreFriends
FindFriendsFragment
FriendRequestsFragment
FriendsListFragment

**Comment by anarten** [comment]
Just need to do Friends and Maps classes
