### ISSUE TITLE
WOW :D Milestones and notifications

### ISSUE THREAD

**Issue by Mara2020** [CMPUT301F17T02/BAARD#92]
Plan:
Milestones 
- Two versions of milestones; overall milestones and streak milestones
---- Ex. Done this habit for two weeks straight (streak) vs going swimming 50 times (just an overall milestone)
- provide reminders to people when they are about to lose a streak. This should happen once someone has done a certain number in a row.. to be commented on
- show milestones on the habit view! friends can see this as well.

**Comment by anarten** [comment]
Streaks have been implemented that "Youre on a streak!" if the 5 most recent frequency days have events. 
Milestones are overall "you've done this many"
Notifications are sent at 4pm if you're going to lose a streak, no matter how long. Anything over 5 days is treated the same.
