### ISSUE TITLE
Permissions and Storage of Images

### ISSUE THREAD

**Issue by anarten** [CMPUT301F17T02/BAARD#98]
Currently for Create/Edit Event, you can select "Image" and pick the image from gallery but once you return to the app and it prompts for permissions if you say no then it crashes. 

Also, if you previously had permissions and set an image, but now you no longer have permission (say using a new phone) then the images are not displayed in view event thus they are currently NOT being saved to server but rather just looking at the local filepath.

**Comment by Mara2020** [comment]
@AndrewMcKernan fixed this issue
